---
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
# enable building on container-based infrastructure
sudo: false
install:
  # install dependencies
  - CFLAGS="-O0" pip install -r requirements.txt
script:
  # unit test schedule_parser script
  - ./test_schedule_parser.py
  # validate conference json schema
  - jsonschema -i `date +%Y`/json/data.json `date +%Y`/json/data_schema.json
notifications:
  webhooks:
    # update website on a successful build
    urls:
      - https://hackerspace.gent/newline/pull.php
    on_success: always # default: always
    on_failure: never # default: always
    on_start: never   # default: never
    on_cancel: never # default: always
    on_error: never # default: always
